# This file was generated by GoReleaser. DO NOT EDIT.
cask "searxng-mcp-go" do
  version "1.0.2"

  on_linux do
    on_intel do
      sha256 "90208eba28595e7c70a697dac6df002d81e54e73662f6947b64c35668c435330"
      url "https://github.com/xlionjuan/searxng-mcp-go/releases/download/v#{version}/searxng-mcp-go_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9919fa90bd8dc0136b297e1909e83b0afbe45cfc849ca802c1cc137e49288116"
      url "https://github.com/xlionjuan/searxng-mcp-go/releases/download/v#{version}/searxng-mcp-go_#{version}_linux_arm64.tar.gz"
    end
  end

  name "searxng-mcp-go"
  desc "SearXNG MCP Server — web search via Meta Search Engine"
  homepage "https://github.com/xlionjuan/searxng-mcp-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "searxng-mcp-go"

  # No zap stanza required

end
