# This file was generated by GoReleaser. DO NOT EDIT.
cask "searxng-mcp-go" do
  version "1.0.1"

  on_linux do
    on_intel do
      sha256 "74eb8000dcd1f07fd461a7bd37fb4ef22167c207a9ea904ffb982d37289cb0b3"
      url "https://github.com/xlionjuan/searxng-mcp-go/releases/download/v#{version}/searxng-mcp-go_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "00497dd101564b16f38e96bcc2f6a0fd731fdd904b5b8c9b88835af8a82bb7fd"
      url "https://github.com/xlionjuan/searxng-mcp-go/releases/download/v#{version}/searxng-mcp-go_#{version}_linux_arm64.tar.gz"
    end
  end

  name "searxng-mcp-go"
  desc "SearXNG MCP Server — web search via Meta Search Engine"
  homepage "https://github.com/xlionjuan/searxng-mcp-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "searxng-mcp-go"

  # No zap stanza required

end
