# This file was generated by GoReleaser. DO NOT EDIT.
cask "searxng-mcp-go" do
  version "1.2.0"

  on_linux do
    on_intel do
      sha256 "bcbdd0cf47f9db3e2336e174b5f5962b5c3f3b5a13b544392398eba464ef0787"
      url "https://github.com/xlionjuan/searxng-mcp-go/releases/download/v#{version}/searxng-mcp-go_v#{version}_linux_amd64.tar.zst"
    end
    on_arm do
      sha256 "915ed9ca91b9b51699f9aa47f5cded047e5a1337785b0a4bd8cf5a7734a594ff"
      url "https://github.com/xlionjuan/searxng-mcp-go/releases/download/v#{version}/searxng-mcp-go_v#{version}_linux_arm64.tar.zst"
    end
  end

  name "searxng-mcp-go"
  desc "SearXNG MCP Server — web search via Meta Search Engine"
  homepage "https://github.com/xlionjuan/searxng-mcp-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "searxng-mcp-go"

  # No zap stanza required

end
