# This file was generated by GoReleaser. DO NOT EDIT.
cask "wastebin-mcp-go" do
  version "0.10.0"

  on_linux do
    on_intel do
      sha256 "53d5fa1c269efc4e8085982f503ea6a60dcaff10456713bd63a430ed281274bf"
      url "https://github.com/xlionjuan/wastebin-mcp-go/releases/download/v#{version}/wastebin-mcp-go_v#{version}_linux_amd64.tar.zst"
    end
    on_arm do
      sha256 "92d2c698f763afef5b17f43d3284b63367d93c7a0b5b1a312767c371ab10a105"
      url "https://github.com/xlionjuan/wastebin-mcp-go/releases/download/v#{version}/wastebin-mcp-go_v#{version}_linux_arm64.tar.zst"
    end
  end

  name "wastebin-mcp-go"
  desc "Wastebin MCP Server — paste creation via Wastebin"
  homepage "https://github.com/xlionjuan/wastebin-mcp-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wastebin-mcp-go"

  # No zap stanza required

end
