# This file was generated by GoReleaser. DO NOT EDIT.
cask "wastebin-mcp-go" do
  version "0.11.0"

  on_linux do
    on_intel do
      sha256 "b868baf9b5f027610192ffe5d2fb67e4369b84496accc0e40757dc88554b5c1b"
      url "https://github.com/xlionjuan/wastebin-mcp-go/releases/download/v#{version}/wastebin-mcp-go_v#{version}_linux_amd64.tar.zst"
    end
    on_arm do
      sha256 "2c5ad40b7c2620d44d2babcb02305d6f37abb159a41e0751e0b0e41833a61467"
      url "https://github.com/xlionjuan/wastebin-mcp-go/releases/download/v#{version}/wastebin-mcp-go_v#{version}_linux_arm64.tar.zst"
    end
  end

  name "wastebin-mcp-go"
  desc "Wastebin MCP Server — paste creation via Wastebin"
  homepage "https://github.com/xlionjuan/wastebin-mcp-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wastebin-mcp-go"

  # No zap stanza required

end
