# This file was generated by GoReleaser. DO NOT EDIT.
cask "wastebin-mcp-go" do
  version "0.12.0"

  on_linux do
    on_intel do
      sha256 "a9ea0b2b10acddb565b8b79632319b8371f4991427b29361052ff55379bdb4b8"
      url "https://github.com/xlionjuan/wastebin-mcp-go/releases/download/v#{version}/wastebin-mcp-go_v#{version}_linux_amd64.tar.zst"
    end
    on_arm do
      sha256 "40b67c82d3ab267edc1b51ba440bf778271d03a4861e46ab57d8918c08bcceb5"
      url "https://github.com/xlionjuan/wastebin-mcp-go/releases/download/v#{version}/wastebin-mcp-go_v#{version}_linux_arm64.tar.zst"
    end
  end

  name "wastebin-mcp-go"
  desc "Wastebin MCP Server — paste creation via Wastebin"
  homepage "https://github.com/xlionjuan/wastebin-mcp-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wastebin-mcp-go"

  # No zap stanza required

end
